function fp = krContactConfigFingerprint()
%krContactConfigFingerprint KrContactConfig の内容指紋

cfg = KrContactConfig();
parts = [ ...
    string(cfg.method), ...
    "slackSigmaMult=" + string(cfg.slackSigmaMult), ...
    "minSlackRun=" + string(cfg.minSlackRun), ...
    "obviousSigmaMult=" + string(cfg.obviousSigmaMult), ...
    "positiveSigmaMult=" + string(cfg.positiveSigmaMult), ...
    "minObviousRun=" + string(cfg.minObviousRun), ...
    "baselineFrac=" + string(cfg.baselineFrac), ...
    "baselineMin=" + string(cfg.baselineMinPoints), ...
    "zeroAtContact=" + string(cfg.zeroAtContact), ...
    "minDefStep=" + string(cfg.minDefStepMm)];
fp = strjoin(parts, "|");

end
