function outlierCfg = OutlierConfig()
%OutlierConfig  MAD ベース外れ値除去の既定設定

reg = PredictorRegistry();

outlierCfg = struct( ...
    "modeYieldMad", true, ...
    "modeBaseXMad", true, ...
    "modeRobustMaha", false, ...
    "madZThreshold", 3.5, ...
    "mahaAlpha", 0.975, ...
    "outlierBasePredictors", reg.outlierBasePredictors);

end
