function reg = PredictorRegistry()
%PredictorRegistry 解析パイプラインの説明変数・目的変数の唯一の定義

reg = struct();
reg.targetName = "yieldPointN";

% 説明変数の抽出定義（kr 以外。kr は buildMasterPredictorTable で krTable からマージ）
reg.predictorFieldMap = struct( ...
    "weight", struct("source", "item", "field", "weight"), ...
    "x", struct("source", "size", "field", "x"), ...
    "y", struct("source", "size", "field", "y"), ...
    "z", struct("source", "size", "field", "z"), ...
    "d_eq", struct("source", "derived", "field", "d_eq"), ...
    "c1", struct("source", "burgersFit", "field", "c1_viscous_Ns_per_mm"), ...
    "c2", struct("source", "burgersFit", "field", "c2_retarded_Ns_per_mm"), ...
    "k2", struct("source", "burgersFit", "field", "k2_retarded_N_per_mm"), ...
    "t50", struct("source", "burgersFit", "field", "t50_retardedSec"), ...
    "t95", struct("source", "burgersFit", "field", "t95_retardedSec"), ...
    "vInit", struct("source", "burgersFit", "field", "creepRateInitial_mm_per_s"), ...
    "vLong", struct("source", "burgersFit", "field", "creepRateLongTerm_mm_per_s"), ...
    "delayedRatio", struct("source", "burgersFit", "field", "retardedRatioAtHold"));

% 04_analyze で使う kr 方式（KrMethodRegistry の key を指定）
reg.krAnalyzeKeys = string({ ...
    "pct_s25_w50"; ...
    "force_s05_w05"; ...
    });

nonKrPredictors = string({ ...
    "weight"; ...
    "x"; "y"; "z"; ...
    "d_eq"; ...
    "c1"; ...
    "c2"; ...
    "k2"; ...
    %"t50"; ...
    %"vLong" ...
    });

reg.paramPredictors = [nonKrPredictors(:); "krLs_" + reg.krAnalyzeKeys(:)];

% コホート固定 + 外れ値 MAD の共通基準（paramPredictors と独立）
% kr_* を列挙すると kr 未推定（NaN）試料は complete 前に除外される
reg.outlierBasePredictors = string({ ...
    %"x"; "y"; "z"; "weight"; ...
    "c1"; "k2"; "c2"; ...
    %"kr_force_band_20_40"; ...
    });

reg.waveformNPoints = 2048;
reg.waveformType = "creep";

validatePredictorRegistry(reg);

end

function validatePredictorRegistry(reg)
mapNames = string(fieldnames(reg.predictorFieldMap));
preds = reg.paramPredictors(:);
isKrPred = startsWith(preds, "kr_");
isKrPred = isKrPred | startsWith(preds, "krLs_") | startsWith(preds, "krChord_");
missingMap = preds(~ismember(preds, mapNames) & ~isKrPred);
if ~isempty(missingMap)
    error("PredictorRegistry:BadMap", ...
        "paramPredictors に predictorFieldMap 未定義の列があります: %s", ...
        strjoin(missingMap, ", "));
end

registryKeys = string({KrMethodRegistry().key});
analyzeKeys = reg.krAnalyzeKeys(:);
unknownKeys = analyzeKeys(~ismember(analyzeKeys, registryKeys));
if ~isempty(unknownKeys)
    error("PredictorRegistry:BadKrKey", ...
        "krAnalyzeKeys に KrMethodRegistry 未定義の key があります: %s", ...
        strjoin(unknownKeys, ", "));
end

outlierBase = reg.outlierBasePredictors(:);
isKrOutlier = startsWith(outlierBase, "kr_");
isKrOutlier = isKrOutlier | startsWith(outlierBase, "krLs_") | startsWith(outlierBase, "krChord_");
missingOutlierMap = outlierBase(~isKrOutlier & ~ismember(outlierBase, mapNames));
if ~isempty(missingOutlierMap)
    error("PredictorRegistry:BadOutlierBase", ...
        "outlierBasePredictors に predictorFieldMap 未定義の列があります: %s", ...
        strjoin(missingOutlierMap, ", "));
end
krOutlier = outlierBase(isKrOutlier);
krOutlierKeys = strings(size(krOutlier));
for i = 1:numel(krOutlier)
    if startsWith(krOutlier(i), "krLs_")
        krOutlierKeys(i) = extractAfter(krOutlier(i), "krLs_");
    elseif startsWith(krOutlier(i), "krChord_")
        krOutlierKeys(i) = extractAfter(krOutlier(i), "krChord_");
    else
        krOutlierKeys(i) = extractAfter(krOutlier(i), "kr_");
    end
end
unknownKrOutlier = krOutlierKeys(~ismember(krOutlierKeys, registryKeys));
if ~isempty(unknownKrOutlier)
    error("PredictorRegistry:BadOutlierKrKey", ...
        "outlierBasePredictors の kr_* に KrMethodRegistry 未定義 key があります: %s", ...
        strjoin(unknownKrOutlier, ", "));
end
end