function tbl = pairedComparisonsToTable(summaries, comparisonLabels)
%pairedComparisonsToTable 複数ペア比較を表にまとめる

if nargin < 2 || isempty(comparisonLabels)
    comparisonLabels = repmat({"generic"}, numel(summaries), 1);
end
rows = cell(numel(summaries), 15);
for i = 1:numel(summaries)
    rows(i, :) = pairedComparisonToRow(summaries{i}, comparisonLabels{i});
end
tbl = cell2table(rows, 'VariableNames', { ...
    'modelA', 'modelB', 'comparisonType', ...
    'deltaMae', 'ciDeltaMaeLo', 'ciDeltaMaeHi', ...
    'deltaR2', 'ciDeltaR2Lo', 'ciDeltaR2Hi', ...
    'pWilcoxon', 'pWilcoxonOneSidedImproveA', ...
    'winRateA', 'cohenDz', 'nWinA', 'n'});
end

function summaryRow = pairedComparisonToRow(summary, comparisonLabel)
summaryRow = {char(summary.modelA), char(summary.modelB), char(comparisonLabel), ...
    summary.deltaMae, summary.ciDeltaMae(1), summary.ciDeltaMae(2), ...
    summary.deltaR2, summary.ciDeltaR2(1), summary.ciDeltaR2(2), ...
    summary.pWilcoxonMae, summary.pWilcoxonOneSidedImproveA, ...
    summary.winRateA, summary.cohenDz, summary.nWinA, summary.n};
end
